spring.application.name=CloudMuseum_backend

# DashScope 配置
dashscope.api.key=sk-502e9e61f28e4e29bd837e45d88cf9fb
dashscope.websocket.url=wss://dashscope.aliyuncs.com/api-ws/v1/inference

textchat.api.base-url=http://26.34.92.227:5000
textchat.api.connect-timeout=30000   
textchat.api.read-timeout=30000      

# 服务器端口（可选）
server.port=8081